-- MySQL Workbench Synchronization
-- Generated: 2015-11-11 15:16
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: baycik

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `isell3`.`companies_tree` 
CHANGE COLUMN `branch_id` `branch_id` INT(10) UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT ;

ALTER TABLE `isell3`.`stock_tree` 
DROP COLUMN `path`,
CHANGE COLUMN `branch_id` `branch_id` INT(10) UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT ;

ALTER TABLE isell3.companies_list
ADD COLUMN is_active INT(1) NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
